export default {
  PROCESSING: 'PROCESSING',
  FINISHED: 'FINISHED',
  GENERATE_CODE: 'GENERATE_CODE',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_ONE_PRODUCTS: 'GET_ONE_PRODUCTS',
  CREATE_WISHLIST: 'CREATE_WISHLIST',
  GET_WISHLISTS: 'GET_WISHLISTS',
  DEL_WISH: 'DEL_WISH',
  CREATE_KART: 'CREATE_KART',
  GET_KARTS: 'GET_KARTS',
  DEL_KART: 'DEL_KART',
}

