export default {
  PROCESSING: 'PROCESSING',
  PROCESSING_SMALL_SPIN: 'PROCESSING_SMALL_SPIN',
  FINISHED: 'FINISHED',
  GENERATE_CODE: 'GENERATE_CODE',
  AUTHENTICATE: 'AUTHENTICATE',
  ONBOARD: 'ONBOARD',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_ONE_PRODUCTS: 'GET_ONE_PRODUCTS',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  GET_WISHLISTS: 'GET_WISHLISTS',
  DEL_WISH: 'DEL_WISH',
  ADD_TO_KART: 'ADD_TO_KART',
  GET_KARTS: 'GET_KARTS',
  DEL_KART: 'DEL_KART',
}

